### ISSUE TITLE
service部分のJavaScriptのリファクタリングとエラー対応

### ISSUE THREAD

**Issue by kp047i** [izewfktvy533zjmn/IoTOMATO#26]
## 問題の詳細
- environment.jsないのコードが重複している
- varで定義している変数が存在するため、スコープの誤認識や巻き上げなどの問題が発生する可能性がある
- エラー処理をしていない

## 修正内容
- 重複したコードを関数化
- 変数をletかconstで定義
- エラー処理を加える

**Comment by izewfktvy533zjmn** [comment]
マージされたらクローズしましょう。
